### ISSUE TITLE
ignores freq parameter in config.gcfg

### ISSUE THREAD

**Issue by kreizo** [paulstuart/influxsnmp#1]
Hi,

We can set  freq  = 30 or  freq  = 15 or freq = 60. Netstats page reports change in config file, but values are still written to influxdb at 30s frequency.

**Comment by paulstuart** [comment]
Oops, sorry that I never noticed this report. I'm cleaning up for influx 0.9 and will address this -- if you're still interested :-)

**Comment by paulstuart** [comment]
Fixed.

**Comment by kreizo** [comment]
Hi,

Thanks a buch. I've been living with minimum 1 min. pooling time. I'll try
different values now .Thanks again.
