### ISSUE TITLE
PDU Support?

### ISSUE THREAD

**Issue by dholt** [paulstuart/influxsnmp#14]
Would it be possible to support rack PDUs? The phases/banks/outlets don't seem to get picked up like switch ports do:

<pre>
ubuntu@electric-flowers:~$ ./work/bin/influxsnmp -config work/etc/config.gcfg -verbose -testing
Looking up column names for: 
COLUMNS [rPDU2BankStatusCurrent]
[1.3.6.1.4.1.318.1.1.26.8.3.1.5]
2016/02/28 20:35:02 Connecting to: localhost
2016/02/28 20:35:02 Connected to: localhost
Web interface:
1.3.6.1.4.1.318.1.1.26.8.3.1.5
http://localhost:9501
2016/02/28 20:35:02 ROOT: 1.3.6.1.4.1.318.1.1.26.8.3.1.5 SUFFIX: 1 COL:  NAME: VALUE: 58
2016/02/28 20:35:02 empty col for: 1
2016/02/28 20:35:02 ROOT: 1.3.6.1.4.1.318.1.1.26.8.3.1.5 SUFFIX: 2 COL:  NAME: VALUE: 38
2016/02/28 20:35:02 empty col for: 2
</pre>

**Comment by paulstuart** [comment]
Arbitrary tables/columns are now supported. Note changes to the sample config file
