### ISSUE TITLE
Compatibility with influxdb 0.1X ??

### ISSUE THREAD

**Issue by toni-moreno** [paulstuart/influxsnmp#15]
Has anybody tested this tool with last influxdb 0.10.X or 0.11  version ?

Thank you very much !!!

**Comment by rgelobterFH** [comment]
Haven't had any problem with it on 0.11

**Comment by toni-moreno** [comment]
Yes @rgelobterFH , I'm also doing test with 0.10.3 and OK ; I can close this issue... ;)
