### ISSUE TITLE
Is Influxsnmp able to get data of network devices?

### ISSUE THREAD

**Issue by naxreo** [paulstuart/influxsnmp#17]
I found influxsnmp could not get some correct data system resource like CPU, Load... etc.
## In the code of snmp.go below,

var (
    errorSNMP int
    nameOid   = "1.3.6.1.2.1.31.1.1.1.1" // ifName
## )

oid for network devices was inserted.

In my test,
influxsnmp could get snmp data of CPU, Memory from Linux manchines but couldn't work well with influxdb. T.T;;

**Comment by toni-moreno** [comment]
I've been working in a big refactor of this great tool and now it is able to get any kind of data.

You can see the branch here.

https://github.com/toni-moreno/influxsnmp/tree/first_big_refactor

a sample config  here.

https://github.com/toni-moreno/influxsnmp/blob/first_big_refactor/conf/sample.config.toml

**Comment by vasya4k** [comment]
toni-moreno you are the legend. I have tried to do the same thing previously but did not have time to finish. Also my programming skills are that good yet.

**Comment by paulstuart** [comment]
arbitrary tables are now pollable
