### ISSUE TITLE
Feature reqests

### ISSUE THREAD

**Issue by nitzan-tz** [paulstuart/influxsnmp#3]
Hi 

Its great software but if you can add some features it will help 
1. Add the interface names to the influxdb (e.g ge-0/0/0 ) 
2. Add option to collect all interfaces on a router not just the ones in the portfile
3. Maybe with option to ignore some with regex or include with regex 
4. Add option to collect the ifAlias (it is string ) and add it to the DB so we can display it 

Thanks

Nitzan

**Comment by paulstuart** [comment]
1. Added how? In newly added bulk support that is the default column name
2. Added bulk support (if no portfile is specified).
3. Seems reasonable enough.
4. How should ifAlias be added to db?

**Comment by nitzan-tz** [comment]
Thanks
1. I think this should be the default column name as it is unique in the device
2. Test and it works
3. great ,you can also take the idea from https://github.com/GreggBzz/snmp-interface-poll/blob/master/src/collectors/snmpinterfacediscovery/snmpinterfacediscovery.py where he collect only interface from specific type (ifType) and only interfaces in up state  
4. IfAlias should be a tag I will also like to have the hostname (the snmp name in the configuration ) in another tag (not replacing the ip address in host )

Thanks

Nitzan

**Comment by paulstuart** [comment]
Aliases, regexp filtering and arbitrary table support is now available.
