### ISSUE TITLE
Unable to plot Load,CPU and Memory using influxsnmp !

### ISSUE THREAD

**Issue by gugansankar** [paulstuart/influxsnmp#9]
Using influxsnmp, I can plot network statistics, But unable to plot the other resources value like Load, CPU and Memory.

Verbose Log output:
2016/01/09 22:02:20 ROOT: 1.3.6.1.4.1.2021.10.1.3.1 SUFFIX: 2 COL: web NAME: VALUE: <nil>
2016/01/09 22:02:20 ROOT: 1.3.6.1.4.1.2021.10.1.3.2 SUFFIX: 2 COL: web NAME: VALUE: <nil>
2016/01/09 22:02:20 ROOT: 1.3.6.1.4.1.2021.10.1.3.3 SUFFIX: 2 COL: web NAME: VALUE: <nil>

Config:
[snmp "test_web"]
host   = 10.11.12.202
community = public
port   = 161
timeout = 20
retries = 5
repeat = 0
freq   = 30
portfile =  webports.txt
[mibs "test_web"]
name = ifXEntry
column = ifHCInOctets
column = ifHCOutOctets
column = laLoad1
column = laLoad5
column = laLoad15

oids.txt
laLoad1              1.3.6.1.4.1.2021.10.1.3.1
laLoad           1.3.6.1.4.1.2021.10.1.3
laLoad15             1.3.6.1.4.1.2021.10.1.3.3
laLoad5              1.3.6.1.4.1.2021.10.1.3.2

Snmpwalk output:
 snmpwalk -v2c -c public 10.11.12.202  1.3.6.1.4.1.2021.10.1.3
iso.3.6.1.4.1.2021.10.1.3.1 = STRING: "0.29"
iso.3.6.1.4.1.2021.10.1.3.2 = STRING: "0.36"
iso.3.6.1.4.1.2021.10.1.3.3 = STRING: "0.36"

**Comment by gugansankar** [comment]
Any idea, please help on this.

**Comment by paulstuart** [comment]
I'll take a look tomorrow.

**Comment by paulstuart** [comment]
In the mibs entry of the config you have laLoad as columns under ifXEntry, which they are not members of. The basic scheme is that the 'name' entry is the main table of interest, the 'columns' are the columns within that table of interest, and the port file is to identify/name the entries from those columns that should be saved.

If you can identify the main table that laLoad belongs to and replace ifXEntry with that you should be good.

I need to take a whack at actually documenting this thing :-)

**Comment by gugansankar** [comment]
Thanks for your reply. I have changed my config as you said. But getting some other error. Could you please help me ?. or Please share example config for my setup.

Config:
[snmp "test_web"]
host = 10.11.12.202
community = public
port = 161
timeout = 20
retries = 5
repeat = 0
freq = 30
portfile = webports.txt
[mibs "test_web"]
name = laLoad
column = laLoad1
column = laLoad5
column = laLoad15
[influx "*"]
host = localhost
port = 8086
db   = snmp

Webport file entry:
$ cat webports.txt 
laLoad1 web_load1
laLoad5 web_load5
laLoad15 web_load15
$

$ ./influxsnmp -config ../etc/config.gcfg -oids oids.txt -logs $HOME/log -verbose
Looking up column names for: 10.11.12.202
**2016/01/12 09:37:36 No OID found for: laLoad15**
$

But I have oid entry for laLoad15 on my oids.txt file,
$ cat oids.txt | grep laLoad
laLoad1              1.3.6.1.4.1.2021.10.1.3.1
laLoad           1.3.6.1.4.1.2021.10.1.3
laLoad15             1.3.6.1.4.1.2021.10.1.3.3
laLoad5              1.3.6.1.4.1.2021.10.1.3.2
$

**Comment by paulstuart** [comment]
The portfile is for the renaming interfaces name in the table found. I'm
not familiar with the this MIB but I'm guessing these are scalar values.
Try commenting out the portfile entry, as it wouldn't be relevant in this
case.

One other thought -- if you're using this to pull load data from the
servers you may want to look at collectd instead. It can be configured to
send directly to influxdb as well and bypasses the need for polling
externally.

Hope this helps,
Paul

**Comment by gugansankar** [comment]
Ok, I tried commenting out the portfile in the config. this time, i could see some default output where I doesn't see oids that relevant to Load average/CPU/Memory.  

Output After commenting out portfile in config:
2016/01/12 12:20:10 ROOT: 1.3.6.1.2.1.31.1.1.1.6 SUFFIX: 1 COL: Gi0/0 NAME: VALUE: 222320725159626
2016/01/12 12:20:10 ROOT: 1.3.6.1.2.1.31.1.1.1.6 SUFFIX: 2 COL: Gi0/1 NAME: VALUE: 757321740307807
2016/01/12 12:20:10 ROOT: 1.3.6.1.2.1.31.1.1.1.6 SUFFIX: 3 COL: Fa0/1/0 NAME: VALUE: 0
2016/01/12 12:20:10 ROOT: 1.3.6.1.2.1.31.1.1.1.6 SUFFIX: 4 COL: Fa0/1/1 NAME: VALUE: 0
2016/01/12 12:20:10 ROOT: 1.3.6.1.2.1.31.1.1.1.6 SUFFIX: 5 COL: Fa0/1/2 NAME: VALUE: 0
2016/01/12 12:20:10 ROOT: 1.3.6.1.2.1.31.1.1.1.6 SUFFIX: 6 COL: Fa0/1/3 NAME: VALUE: 0
2016/01/12 12:20:10 ROOT: 1.3.6.1.2.1.31.1.1.1.6 SUFFIX: 9 COL: Vl1 NAME: VALUE: 0
2016/01/12 12:20:10 ROOT: 1.3.6.1.2.1.31.1.1.1.6 SUFFIX: 12 COL: Tu100 NAME: VALUE: 0
2016/01/12 12:20:10 ROOT: 1.3.6.1.2.1.31.1.1.1.6 SUFFIX: 13 COL: Tu200 NAME: VALUE: 0
2016/01/12 12:20:10 ROOT: 1.3.6.1.2.1.31.1.1.1.6 SUFFIX: 20 COL: Tu500 NAME: VALUE: 1309151506
2016/01/12 12:20:10 ROOT: 1.3.6.1.2.1.31.1.1.1.6 SUFFIX: 21 COL: Gi0/0.2 NAME: VALUE: 28467041659831
2016/01/12 12:20:10 ROOT: 1.3.6.1.2.1.31.1.1.1.6 SUFFIX: 23 COL: Gi0/0.3 NAME: VALUE: 117959815551171

2016/01/12 12:20:10 ROOT: 1.3.6.1.2.1.31.1.1.1.7 SUFFIX: 1 COL: Gi0/0 NAME: VALUE: 498551280119
2016/01/12 12:20:10 ROOT: 1.3.6.1.2.1.31.1.1.1.7 SUFFIX: 2 COL: Gi0/1 NAME: VALUE: 699548823034
2016/01/12 12:20:10 ROOT: 1.3.6.1.2.1.31.1.1.1.7 SUFFIX: 3 COL: Fa0/1/0 NAME: VALUE: 0
2016/01/12 12:20:10 ROOT: 1.3.6.1.2.1.31.1.1.1.7 SUFFIX: 4 COL: Fa0/1/1 NAME: VALUE: 0
2016/01/12 12:20:10 ROOT: 1.3.6.1.2.1.31.1.1.1.7 SUFFIX: 5 COL: Fa0/1/2 NAME: VALUE: 0
2016/01/12 12:20:10 ROOT: 1.3.6.1.2.1.31.1.1.1.7 SUFFIX: 6 COL: Fa0/1/3 NAME: VALUE: 0
2016/01/12 12:20:10 ROOT: 1.3.6.1.2.1.31.1.1.1.7 SUFFIX: 9 COL: Vl1 NAME: VALUE: 0
2016/01/12 12:20:10 ROOT: 1.3.6.1.2.1.31.1.1.1.7 SUFFIX: 12 COL: Tu100 NAME: VALUE: 0
2016/01/12 12:20:10 ROOT: 1.3.6.1.2.1.31.1.1.1.7 SUFFIX: 13 COL: Tu200 NAME: VALUE: 0
2016/01/12 12:20:10 ROOT: 1.3.6.1.2.1.31.1.1.1.7 SUFFIX: 20 COL: Tu500 NAME: VALUE: 1571914
2016/01/12 12:20:10 ROOT: 1.3.6.1.2.1.31.1.1.1.7 SUFFIX: 21 COL: Gi0/0.2 NAME: VALUE: 137388265721
2016/01/12 12:20:10 ROOT: 1.3.6.1.2.1.31.1.1.1.7 SUFFIX: 23 COL: Gi0/0.3 NAME: VALUE: 160652325743
2016/01/12 12:20:10 ROOT: 1.3.6.1.2.1.31.1.1.1.10 SUFFIX: 1 COL: Gi0/0 NAME: VALUE: 758911315445142
2016/01/12 12:20:10 ROOT: 1.3.6.1.2.1.31.1.1.1.10 SUFFIX: 2 COL: Gi0/1 NAME: VALUE: 219692918205477
2016/01/12 12:20:10 ROOT: 1.3.6.1.2.1.31.1.1.1.10 SUFFIX: 3 COL: Fa0/1/0 NAME: VALUE: 0
2016/01/12 12:20:10 ROOT: 1.3.6.1.2.1.31.1.1.1.10 SUFFIX: 4 COL: Fa0/1/1 NAME: VALUE: 0
2016/01/12 12:20:10 ROOT: 1.3.6.1.2.1.31.1.1.1.10 SUFFIX: 5 COL: Fa0/1/2 NAME: VALUE: 0
2016/01/12 12:20:10 ROOT: 1.3.6.1.2.1.31.1.1.1.10 SUFFIX: 6 COL: Fa0/1/3 NAME: VALUE: 0
2016/01/12 12:20:10 ROOT: 1.3.6.1.2.1.31.1.1.1.10 SUFFIX: 9 COL: Vl1 NAME: VALUE: 6096552
2016/01/12 12:20:10 ROOT: 1.3.6.1.2.1.31.1.1.1.10 SUFFIX: 12 COL: Tu100 NAME: VALUE: 0
2016/01/12 12:20:10 ROOT: 1.3.6.1.2.1.31.1.1.1.10 SUFFIX: 13 COL: Tu200 NAME: VALUE: 0
2016/01/12 12:20:10 ROOT: 1.3.6.1.2.1.31.1.1.1.10 SUFFIX: 20 COL: Tu500 NAME: VALUE: 0
2016/01/12 12:20:10 ROOT: 1.3.6.1.2.1.31.1.1.1.10 SUFFIX: 21 COL: Gi0/0.2 NAME: VALUE: 284831980719838
2016/01/12 12:20:10 ROOT: 1.3.6.1.2.1.31.1.1.1.10 SUFFIX: 23 COL: Gi0/0.3 NAME: VALUE: 162586750948068
2016/01/12 12:20:10 ROOT: 1.3.6.1.2.1.31.1.1.1.11 SUFFIX: 1 COL: Gi0/0 NAME: VALUE: 699746615838
2016/01/12 12:20:10 ROOT: 1.3.6.1.2.1.31.1.1.1.11 SUFFIX: 2 COL: Gi0/1 NAME: VALUE: 497688896156
2016/01/12 12:20:10 ROOT: 1.3.6.1.2.1.31.1.1.1.11 SUFFIX: 3 COL: Fa0/1/0 NAME: VALUE: 0
2016/01/12 12:20:10 ROOT: 1.3.6.1.2.1.31.1.1.1.11 SUFFIX: 4 COL: Fa0/1/1 NAME: VALUE: 0
2016/01/12 12:20:10 ROOT: 1.3.6.1.2.1.31.1.1.1.11 SUFFIX: 5 COL: Fa0/1/2 NAME: VALUE: 0
2016/01/12 12:20:10 ROOT: 1.3.6.1.2.1.31.1.1.1.11 SUFFIX: 6 COL: Fa0/1/3 NAME: VALUE: 0
2016/01/12 12:20:10 ROOT: 1.3.6.1.2.1.31.1.1.1.11 SUFFIX: 9 COL: Vl1 NAME: VALUE: 79176
2016/01/12 12:20:10 ROOT: 1.3.6.1.2.1.31.1.1.1.11 SUFFIX: 12 COL: Tu100 NAME: VALUE: 0
2016/01/12 12:20:10 ROOT: 1.3.6.1.2.1.31.1.1.1.11 SUFFIX: 13 COL: Tu200 NAME: VALUE: 0
2016/01/12 12:20:10 ROOT: 1.3.6.1.2.1.31.1.1.1.11 SUFFIX: 20 COL: Tu500 NAME: VALUE: 0
2016/01/12 12:20:10 ROOT: 1.3.6.1.2.1.31.1.1.1.11 SUFFIX: 21 COL: Gi0/0.2 NAME: VALUE: 221789518061
2016/01/12 12:20:10 ROOT: 1.3.6.1.2.1.31.1.1.1.11 SUFFIX: 23 COL: Gi0/0.3 NAME: VALUE: 195903278634

Could you please share some configuration example for Load/Memory/CPU and share oids relevant to these ?

**Comment by paulstuart** [comment]
I've only used this software for polling network hardware -- I don't have
any experience with OS MIBs.

**Comment by gugansankar** [comment]
Oh Okay Fine.

In future, Do you have any idea to support OS MIBs ?.

**Comment by paulstuart** [comment]
It's not about OS vs. Networks MIBs; in a sense they are all the same. The
issue here appears to be scaler vs. tabular data. This code was originally
written to poll tabular data. From the last email it appeared that you
_were_ getting data, so I'm not sure what problems remain.

I've actually been unable to use this code for the purpose I originally
envisioned, so I've not spent any time on it lately (but plan to get it
into prod again).

**Comment by paulstuart** [comment]
Any column is supported as long as the mib data is available
